server:
  port: 39123

spring:
  cache:
    ehcache:
      config: classpath:ehcache/ehcache-spring.xml
  redis:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 1000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.database.horsecoder.com:3306/horsecoder?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: HorseCoder3030!@
    druid:
      driver-class-name: ${spring.datasource.driver-class-name}
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      initial-size: 2
      max-active: 10
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

eureka:
  client:
    service-url:
      defaultZone: http://dev.center.horsecoder.com:11096/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
    status-page-url-path: /info
    health-check-url-path: /health